#install.packages("singleRcapture")
remotes::install_github("https://github.com/ncn-foreigners/singleRcapture/tree/development", force = TRUE)
library(singleRcapture)

##### data generated by ztoipoisson ####

# pop size
N <- 1000
sims <- 500

fn <- ztoipoisson(
  lambdaLink = "log",
  omegaLink = "cloglog"
)

# correct distribution, wrong link
fn1 <- ztoipoisson(
  omegaLink = "logit"
)

# geometric distribution
fn2 <- ztoigeom(
  omegaLink = "cloglog"
)

# Hurdle
fn3 <- ztHurdlepoisson(
  piLink = "logit"
)

fn4 <- Hurdleztpoisson(
  piLink = "logit"
)

#oizt
fn5 <- oiztpoisson(
  omegaLink = "cloglog"
)

res <- matrix(ncol = 6, nrow = sims)

set.seed(123)

for (k in 1L:sims) {
  cat("\nSimulation number: ", k, "\n--------", sep = "")
  # covariates
  x1 <-  runif(n = N)
  x2 <- rbinom(n = N, size = 30, prob = .4)
  x3 <-  rpois(n = N, lambda = 3)
  x4 <- rbinom(n = N, prob = .5, size = 1)
  eta <- cbind(
    cbind(1, x1, x2, x3, x4) %*% c(.2, 1, -.1, .2, -.75),
    cbind(1, x1, x2, x3, x4) %*% c(-1, -2, .05, -.1, .9)
  )
  
  y <- fn$simulate(n = N, eta = eta, lower = -1)
  
  df <- data.frame(
    y = y, x1 = x1, x2 = x2, x3 = x3, x4 = x4
  )
  
  df <- df[df$y>0, ]
  
  M  <- NA
  M1 <- NA
  M2 <- NA
  M3 <- NA
  M4 <- NA
  M5 <- NA
  
  try(
    M <- popSizeEst(estimatePopsize(
      formula = y ~ .,
      data = df,
      model = fn,
      controlModel = controlModel(
        omegaFormula = ~ .
      ),
      controlMethod = controlMethod(
        silent = TRUE
      )
    ))[["pointEstimate"]],
    silent = TRUE
  )
  
  try(
    M1 <- popSizeEst(estimatePopsize(
      formula = y ~ .,
      data = df,
      model = fn1,
      controlModel = controlModel(
        omegaFormula = ~ .
      ),
      controlMethod = controlMethod(
        silent = TRUE
      )
    ))[["pointEstimate"]],
    silent = TRUE
  )
  
  try(
    M2 <- popSizeEst(estimatePopsize(
      formula = y ~ .,
      data = df,
      model = fn2,
      controlModel = controlModel(
        omegaFormula = ~ .
      ),
      controlMethod = controlMethod(
        silent = TRUE
      )
    ))[["pointEstimate"]],
    silent = TRUE
  )
  
  try(
    M3 <- popSizeEst(estimatePopsize(
      formula = y ~ .,
      data = df,
      model = fn3,
      controlModel = controlModel(
        piFormula = ~ .
      ),
      controlMethod = controlMethod(
        silent = TRUE
      )
    ))[["pointEstimate"]],
    silent = TRUE
  )
  
  try(
    M4 <- popSizeEst(estimatePopsize(
      formula = y ~ .,
      data = df,
      model = fn4,
      controlModel = controlModel(
        piFormula = ~ .
      ),
      controlMethod = controlMethod(
        silent = TRUE
      )
    ))[["pointEstimate"]],
    silent = TRUE
  )
  
  try(
    M5 <- popSizeEst(estimatePopsize(
      formula = y ~ .,
      data = df,
      model = fn5,
      controlModel = controlModel(
        omegaFormula = ~ .
      ),
      controlMethod = controlMethod(
        silent = TRUE
      )
    ))[["pointEstimate"]],
    silent = TRUE
  )
  
  res[k, ] <- c(M, M1, M2, M3, M4, M5)
}

##### data generated by oiztpoisson ####

##### data generated by ztHurdlepoisson ####

##### data generated by Hurdleztpoisson ####
